### ISSUE TITLE
[Bug Report] ModuleNotFoundError

### ISSUE THREAD

**Issue by loveisacat** [Farama-Foundation/MiniGrid#243]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

I installed the latest version of minigrid according to the README.md file. I have the following problem, could this be caused by the latest rename changes?

**Describe the bug**
(maze) a123@MacBookPro MiniGrid % ./minigrid/manual_control.py
Traceback (most recent call last):
  File "/Users/a123/Documents/codebase/MiniGrid/./minigrid/manual_control.py", line 3, in <module>
    import gym
  File "/opt/homebrew/lib/python3.9/site-packages/gym/__init__.py", line 15, in <module>
    from gym.envs import make, spec, register
  File "/opt/homebrew/lib/python3.9/site-packages/gym/envs/__init__.py", line 5, in <module>
    _load_env_plugins()
  File "/opt/homebrew/lib/python3.9/site-packages/gym/envs/registration.py", line 305, in load_env_plugins
    fn = plugin.load()
  File "/opt/homebrew/lib/python3.9/site-packages/importlib_metadata-4.12.0-py3.9.egg/importlib_metadata/__init__.py", line 203, in load
    module = import_module(match.group('module'))
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/a123/Documents/codebase/MiniGrid/minigrid/minigrid.py", line 13, in <module>
    from minigrid.rendering import (
ModuleNotFoundError: No module named 'minigrid.rendering'; 'minigrid' is not a package

**Code example**
Please try to provide a minimal example to reproduce the bug. Error messages and stack traces are also helpful.

**System Info**
Describe the characteristic of your environment:
 * Describe how `minigrid` was installed (pip, docker, source, ...)
 pip install as README
 * What OS/version of Linux you're using. Note that while we will accept PRs to improve Window's support, we do not officially support it.
 MacOS Monterey 12.5.1
 * Python version
 Python 3.9.13

### Checklist

- [ ] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/MiniGrid/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for spotting this, this was fixed in #244
