### ISSUE TITLE
[Bug Report] self.fig.canvas.set_window_title(title) API deprecated

### ISSUE THREAD

**Issue by colourfulspring** [Farama-Foundation/Minigrid#384]
**Describe the bug**
I tried to render a single env, but I got this error:
```text
Traceback (most recent call last):
  File "/home/drl/Projects/Paper1/paired/test.py", line 5, in <module>
    env.render()
  File "/home/drl/miniconda3/envs/UED/lib/python3.8/site-packages/gym_minigrid/minigrid.py", line 1241, in render
    self.window = gym_minigrid.window.Window('gym_minigrid')
  File "/home/drl/miniconda3/envs/UED/lib/python3.8/site-packages/gym_minigrid/window.py", line 26, in __init__
    self.fig.canvas.set_window_title(title)
AttributeError: 'FigureCanvasTkAgg' object has no attribute 'set_window_title'
```
**Code example**
```python
import gym 
import gym_minigrid

env = gym.make('MiniGrid-GoToDoor-8x8-v0')
env.render()
```

**System Info**
Describe the characteristic of your environment:
 * Describe how `minigrid` was installed (pip, docker, source, ...)     (pip)
 * What OS/version of Linux you're using. Note that while we will accept PRs to improve Window's support, we do not officially support it.   (Ubuntu 20.04)
 * Python version (3.8.17)

**Additional context**
[Someone](https://github.com/raysect/source/issues/383) said that new version of matplotlib had removed the `fig.canvas.set_window_title` API, but I found at File "gym_minigrid/window.py", line 26, in `__init__` , there is a calling `self.fig.canvas.set_window_title(title)`. I have tried to change it to `self.fig.canvas.manager.set_window_title(title)` as the issue said, then the error disappered.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/MiniGrid/issues) in the repo (**required**)

**Comment by colourfulspring** [comment]
Oh I found that I install the `gym_minigrid` instead of `minigrid`, I will correct this and try again
