### ISSUE TITLE
[Bug Report] Error when creating BabyAI environment

### ISSUE THREAD

**Issue by chang-github-00** [Farama-Foundation/Minigrid#387]
**Describe the bug**
Can't create an environment from BabyAI.

**Code example**
```python
import gymnasium
gymnasium.make("BabyAI-GoToRedBall-v0")
```

got error:

```console
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/v-changma1/miniconda3/envs/agent/lib/python3.9/site-packages/gymnasium/core.py", line 469, in __repr__
    return str(self)
  File "/home/v-changma1/miniconda3/envs/agent/lib/python3.9/site-packages/gymnasium/core.py", line 465, in __str__
    return f"<{type(self).__name__}{self.env}>"
  File "/home/v-changma1/miniconda3/envs/agent/lib/python3.9/site-packages/gymnasium/core.py", line 465, in __str__
    return f"<{type(self).__name__}{self.env}>"
  File "/home/v-changma1/miniconda3/envs/agent/lib/python3.9/site-packages/minigrid/minigrid_env.py", line 201, in __str__
    if i == self.agent_pos[0] and j == self.agent_pos[1]:
TypeError: 'NoneType' object is not subscriptable
```

**System Info**
Describe the characteristic of your environment:
`pip install minigrid==2.3.0`
 * What OS/version of Linux you're using. Note that while we will accept PRs to improve Window's support, we do not officially support it: Ubuntu 20.04
 * Python version: 3.9

### Checklist

- [ ] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/MiniGrid/issues) in the repo (**required**)

**Comment by BolunDai0216** [comment]
Can you check if you run `env = gymnasium.make("BabyAI-GoToRedBall-v0")` does it still produce the same error?

**Comment by chang-github-00** [comment]
Thanks, this could be solved with ```env = gymnasium.make("BabyAI-GoToRedBall-v0")```
